# run with docker-compose up -d
services:
  frontend:
    build: ./frontend
    container_name: cloudsight-frontend
    ports:
      - "3000:3000"   # React app
    restart: unless-stopped
  
  neo4j:
    image: neo4j:5.15
    container_name: cloudsight-neo4j
    ports:
      - "7474:7474"   # Neo4j Browser (http://localhost:7474)
      - "7687:7687"   # for Python connection - Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      # Mounts init-scripts folder into Neo4j's import directory
      - ./neo4j/init-scripts:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    restart: unless-stopped

  neo4j-init:
    image: neo4j:5.15
    container_name: cloudsight-neo4j-init
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./neo4j/init-scripts:/var/lib/neo4j/import
    environment:
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    command: >
      bash -c "cypher-shell -a bolt://neo4j:7687 -u $$NEO4J_USER -p $$NEO4J_PASSWORD --file /var/lib/neo4j/import/schema.cypher && echo 'Schema applied successfully'"
    restart: "no"

volumes:
  neo4j_data:
  neo4j_logs: